#!/usr/bin/env python
"""Script for generation table with data/models from list.json in .md format"""
import argparse
import json
import os


DATASETS_SOURCE = "list.json"


def generate_table(fn):
    with open(fn) as infile:
        data = json.loads(infile.read())

    datasets = sorted(data["corpora"].items(), key=lambda kv: kv[0])
    models = sorted(data["models"].items(), key=lambda kv: kv[0])

    print("## Available data")
    print("### Datasets")
    print("| name | source | description |")
    print("|------|--------|-------------|")
    for name, other in datasets:
        if name.startswith("__testing_"):
            continue
        print("| {name} | {source} | {description} |".format(
            name=name, source=other["source"], description=other["description"]
        ))

    print("")
    print("### Models")
    print("| name | description | papers | preprocessing | parameters |")
    print("|------|-------------|------------|--------|---------------|")
    for name, other in models:
        if name.startswith("__testing_"):
            continue
        print("| {name} | {description} | {papers} | {preprocessing} | {parameters} |".format(
            name=name, description=other["description"], parameters=other.get("parameters", "-"),
            papers=other.get("papers", "-"), preprocessing=other.get("preprocessing", "-")
        ))
    print("(generated by {} based on {})".format(__file__, os.path.basename(fn)))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-file", help="Path to {}".format(DATASETS_SOURCE), default=DATASETS_SOURCE)
    args = parser.parse_args()
    generate_table(args.input_file)


if __name__ == "__main__":
    main()
